/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Users.Airline;
import Business.Users.Customer;
import Business.Users.TravelAgent;
import Business.Users.User;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author apple
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */

    JPanel userProcessContainer;
    LoginPanel(JPanel userProcessContainer) {
        this.userProcessContainer = userProcessContainer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboUser = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        txtPassword1 = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(750, 700));

        comboUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the type of User", "Customer", "Airline", "Travel Agency" }));

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel3.setText("Not an user? Register here");

        btnRegister.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(2, 2, 2)
                                .addComponent(btnRegister))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(txtUserName))
                                .addGap(29, 29, 29)
                                .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(btnLogin)))
                .addGap(0, 153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnRegister))
                .addContainerGap(457, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add(new SignUpPanel(userProcessContainer));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        String role = (String)comboUser.getSelectedItem();
        ArrayList<String> messageLog = new ArrayList<>();
        if(txtUserName.getText().equals("") || txtPassword1.getText().equals("")) { 
            messageLog.add("User name and/or Password cannot be empty");
        }
        if(role.equals("Customer")) {
            boolean customerFound = false;
            for(User cust: Business.BusinessUtils.getCustomerDirectory().getCustomerList()) {
                if(txtUserName.getText().equals(cust.getUserName()) && txtPassword1.getText().equals(cust.getPassword())) {
                    customerFound = true;
                    userProcessContainer.add(new CustomerHomePanel(userProcessContainer,(Customer)cust));
                    layout.next(userProcessContainer);
                }
                
            }
            if(!customerFound) {
                messageLog.add("Incorrect Customer credentials!\nPlease check your input and try again!");
            }
        }
        else if(role.equals("Travel Agency")) {
            boolean taFound = false;
            for(User travelAgent: Business.BusinessUtils.getTravelAgentDirectory().getTravelAgentList()) {
                if(txtUserName.getText().equals(travelAgent.getUserName()) && txtPassword1.getText().equals(travelAgent.getPassword())) {
                    taFound = true;
                    userProcessContainer.add(new TravelAgentMgmtPanel(userProcessContainer, (TravelAgent)travelAgent));
                    layout.next(userProcessContainer);
                }
            }
            if(!taFound) {
                messageLog.add("Incorrect Travel Agent credentials!\nPlease check your input and try again!");
            }
        }
        else if(role.equals("Airline")) {
            boolean airlineFound = false;
            for(User airline: Business.BusinessUtils.getAirlineDirectory().getAirlineList()) {
                if(txtUserName.getText().equals(airline.getUserName()) && txtPassword1.getText().equals(airline.getPassword())) {
                    airlineFound = true;
                    if(((Airline)airline).getIsAirlineCreated()) {
                        userProcessContainer.add(new FlightMgmtPanel(userProcessContainer, (Airline)airline));
                        layout.next(userProcessContainer);
                        break;
                    }
                    else{
                        userProcessContainer.add(new AirlineCreatePanel(userProcessContainer, (Airline)airline));
                        layout.next(userProcessContainer);
                        break;
                    }
                }
            }
            if(!airlineFound) {
                messageLog.add("Incorrect Airline credentials!\nPlease check your input and try again!");
            }
        }
        else {
            messageLog.add("Please select a role and try again!");
        }
        if(!messageLog.isEmpty()) {
            String errorLog="";
            for(String message: messageLog)
            errorLog+=message+"\n";
            JOptionPane.showMessageDialog(null,errorLog);
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> comboUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
