/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.BusinessUtils;
import Business.Components.AirlineDirectory;
import Business.Components.Flight;
import Business.Components.FlightDirectory;
import Business.Components.Ticket;
import Business.Components.TicketDirectory;
import Business.Users.Airline;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apple
 */
public class ManageAirlinePanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinePanel
     */
    private AirlineDirectory airlineList;
    private FlightDirectory flightList;
    private TicketDirectory ticketList;
    private JPanel userProcessContainer;
    public ManageAirlinePanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        airlineList=BusinessUtils.getAirlineDirectory();
        ticketList=BusinessUtils.getTicketDirectory();
        populateTable();
    }
    
     public void populateTable(){
        DefaultTableModel dtm=(DefaultTableModel) tblAirline.getModel();
        dtm.setRowCount(0);
        for(Airline airline:airlineList.getAirlineList()){
            Object[] row=new Object[6];
            row[0]=airline.getId();
            row[1]=airline;
            for(Flight flight:airline.getFlightDirectory().getFlightList()){
                row[2]=flight.getFrom();
                row[3]=flight.getTo();
                row[4]=flight;
                row[5]=flight.getArrival();
                dtm.addRow(row);
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirline = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblAirline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Airline ID", "Airline Name", "Flight from", "Flight to", "Departure", "Arrival"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAirline);
        if (tblAirline.getColumnModel().getColumnCount() > 0) {
            tblAirline.getColumnModel().getColumn(0).setResizable(false);
            tblAirline.getColumnModel().getColumn(1).setResizable(false);
            tblAirline.getColumnModel().getColumn(2).setResizable(false);
            tblAirline.getColumnModel().getColumn(3).setResizable(false);
        }

        btnDelete.setText("Delete Airline");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(btnDelete)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAirline.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
             Airline airline = (Airline)tblAirline.getValueAt(selectedRow, 1);
             Flight flight=(Flight)tblAirline.getValueAt(selectedRow, 4);
             airlineList.getAirlineList().remove(airline);
             FlightDirectory flightList=airline.getFlightDirectory();
             flightList.getFlightList().remove(flight);
             
             List<Ticket> list;
                list = Collections.synchronizedList(new ArrayList<Ticket>(ticketList.getTicketList()));
                synchronized(list) {
                    Iterator<Ticket> iter = list.iterator();
                    while (iter.hasNext()) { 
                        Ticket t = iter.next();
                        if(t.getFlight().equals(flight)) {
                            ticketList.getTicketList().remove(t);
                        }
                    } 
                }
             populateTable();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAirline;
    // End of variables declaration//GEN-END:variables
}
