/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Users.Airline;
import Business.Users.Customer;
import Business.Users.TravelAgent;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author pavanrao
 */
public class TravelAgentMgmtPanel extends javax.swing.JPanel {

    /**
     * Creates new form TravelAgentMgmtPanel
     */
    JPanel userProcessContainer;
    TravelAgent travelAgent;
    
    public TravelAgentMgmtPanel(JPanel userProcessContainer, TravelAgent travelAgent) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.travelAgent = travelAgent;
        addCustomers();
    }
    
    public void addCustomers(){
        for(Customer c:Business.BusinessUtils.getCustomerDirectory().getCustomerList()){
            comboCustomers.addItem(c.getUserName());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageAirline = new javax.swing.JButton();
        btnNewBooking = new javax.swing.JButton();
        btnManageBooking = new javax.swing.JButton();
        comboCustomers = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(750, 700));

        btnManageAirline.setText("MANAGE AIRLINES");
        btnManageAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAirlineActionPerformed(evt);
            }
        });

        btnNewBooking.setText("NEW BOOKING");
        btnNewBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewBookingActionPerformed(evt);
            }
        });

        btnManageBooking.setText("MANAGE BOOKING");
        btnManageBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBookingActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnNewBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageBooking))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addComponent(btnManageAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnManageAirline)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(comboCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNewBooking)
                .addGap(18, 18, 18)
                .addComponent(btnManageBooking)
                .addContainerGap(387, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewBookingActionPerformed
        // TODO add your handling code here:
        Customer customer=null;
            for(Customer c:Business.BusinessUtils.getCustomerDirectory().getCustomerList()){
                if(comboCustomers.getSelectedItem().toString().equals(c.getUserName()));
                {
                    customer=c;
                }
            }
        
        CustomerBookFlightPanel panel=new CustomerBookFlightPanel(userProcessContainer,customer); 
        userProcessContainer.add("CustomerBookFlightPanel",panel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNewBookingActionPerformed

    private void btnManageBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBookingActionPerformed
        // TODO add your handling code here:
        Customer customer=null;
            for(Customer c:Business.BusinessUtils.getCustomerDirectory().getCustomerList()){
                if(comboCustomers.getSelectedItem().toString().equals(c.getUserName()));
                {
                    customer=c;
                }
            }
        CustomerManageBooking panel=new CustomerManageBooking(userProcessContainer, customer);
        userProcessContainer.add("CustomerManageBooking",panel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageBookingActionPerformed

    private void btnManageAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAirlineActionPerformed
        // TODO add your handling code here:
        ManageAirlinePanel panel=new ManageAirlinePanel(userProcessContainer);
        userProcessContainer.add("CustomerManageBooking",panel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAirlineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAirline;
    private javax.swing.JButton btnManageBooking;
    private javax.swing.JButton btnNewBooking;
    private javax.swing.JComboBox<String> comboCustomers;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
