/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pavanrao
 */
public class UpdateCarDetailsPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateCarDetailsPanel
     */
    private JPanel carContainer;
    private Car car;
    public static String modifiedOn;
    
    UpdateCarDetailsPanel(JPanel carContainer, Car car) {
        this.car = car;
        this.carContainer = carContainer;
        initComponents();
        txtAvailableCity.setText(car.getAvailble_city());
        txtBrand.setText(car.getBrand());
        txtManufacturedYear.setText(Integer.toString(car.getManufactured_year()));
        txtMaxSeats.setText(Integer.toString(car.getMax_seats()));
        txtMinSeats.setText(Integer.toString(car.getMin_seats()));
        txtModelNo.setText(car.getModel_num());
        txtSerialNo.setText(Integer.toString(car.getSerial_num()));
        checkYes.setSelected(car.isAvailable());
        checkExpired.setSelected(car.isMaintenance_certificate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        checkExpired = new javax.swing.JCheckBox();
        labelMaintCertStatus = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        labelAvailable = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        labelRegister = new javax.swing.JLabel();
        txtManufacturedYear = new javax.swing.JTextField();
        labelBrand = new javax.swing.JLabel();
        txtMinSeats = new javax.swing.JTextField();
        labelManufacturedYear = new javax.swing.JLabel();
        txtMaxSeats = new javax.swing.JTextField();
        labelMinSeats = new javax.swing.JLabel();
        txtSerialNo = new javax.swing.JTextField();
        labelMaxSeats = new javax.swing.JLabel();
        txtModelNo = new javax.swing.JTextField();
        labelSerialNo = new javax.swing.JLabel();
        txtAvailableCity = new javax.swing.JTextField();
        labelModelNo = new javax.swing.JLabel();
        checkYes = new javax.swing.JCheckBox();
        labelAvailableCity = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        btnBack.setText("< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        checkExpired.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        checkExpired.setText("Active");

        labelMaintCertStatus.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelMaintCertStatus.setText("MAINTENANCE CERTIFICATE STATUS");

        btnUpdate.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        labelAvailable.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelAvailable.setText("AVAILABLE");

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        labelRegister.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        labelRegister.setText("UPDATE CAR");

        txtManufacturedYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturedYearActionPerformed(evt);
            }
        });

        labelBrand.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelBrand.setText("BRAND");

        labelManufacturedYear.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelManufacturedYear.setText("MANUFACTURED YEAR");

        labelMinSeats.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelMinSeats.setText("MINIMUM SEATS");

        labelMaxSeats.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelMaxSeats.setText("MAXIMUM SEATS");

        labelSerialNo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelSerialNo.setText("SERIAL NUMBER");

        labelModelNo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelModelNo.setText("MODEL NUMBER");

        checkYes.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        checkYes.setText("Yes");

        labelAvailableCity.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelAvailableCity.setText("AVAILABLE CITY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(484, 484, 484))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(315, 315, 315)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelManufacturedYear, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelMinSeats, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelMaxSeats, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelSerialNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelModelNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelAvailableCity, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelMaintCertStatus, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelAvailable, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelBrand, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(77, 77, 77)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkYes)
                            .addComponent(checkExpired)
                            .addComponent(txtAvailableCity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtModelNo)
                            .addComponent(txtBrand)
                            .addComponent(txtManufacturedYear)
                            .addComponent(txtMinSeats)
                            .addComponent(txtMaxSeats)
                            .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(573, 573, 573)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(452, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBrand))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelManufacturedYear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMinSeats))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMaxSeats))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSerialNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelModelNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAvailableCity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAvailableCity))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkExpired)
                    .addComponent(labelMaintCertStatus))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkYes)
                    .addComponent(labelAvailable))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        carContainer.remove(this);
        CardLayout layout = (CardLayout) carContainer.getLayout();
        Component[] comps = this.carContainer.getComponents();
        for(Component comp: comps) {
            if(comp instanceof UpdateCarJPanel) {
                UpdateCarJPanel updateCar = (UpdateCarJPanel) comp;
                updateCar.populate();
            }
        }
        layout.previous(carContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        ArrayList<String> messageLog = new ArrayList<>();
        Boolean available, expired;
        String brand = txtBrand.getText();
        String modelNum = txtModelNo.getText();
        String availableCity = txtAvailableCity.getText();
        
        String year = txtManufacturedYear.getText();
        int manufacturedYear = 0;
        try 
        {
            Integer.parseInt(year);
            manufacturedYear = Integer.parseInt(year);        
        } 
        catch (NumberFormatException e) 
        {
            messageLog.add(year + " is not a valid number.");
        }
        
        String minSeats = txtMinSeats.getText();
        int miniSeats = 0;
        try 
        {
            Integer.parseInt(minSeats);
            miniSeats = Integer.parseInt(minSeats);        
        } 
        catch (NumberFormatException e) 
        {
            messageLog.add(minSeats + " is not a valid number.");
        }
        
        String maxSeats = txtMaxSeats.getText();
        int maxiSeats = 0;
        try 
        {
            Integer.parseInt(maxSeats);
            maxiSeats = Integer.parseInt(maxSeats);        
        } 
        catch (NumberFormatException e) 
        {
            messageLog.add(maxSeats + " is not a valid number.");
        }
        
        String serNo = txtSerialNo.getText();
        int serialNo = 0;
        try 
        {
            Integer.parseInt(serNo);
            serialNo = Integer.parseInt(serNo);        
        } 
        catch (NumberFormatException e) 
        {
            messageLog.add(serNo + " is not a valid number.");
        }

        if(checkYes.isSelected()) {
            available = true;
        }
        else {
            available = false;
        }
        if(checkExpired.isSelected()) {
            expired = true;
        }
        else {
            expired = false;
        }

        if(messageLog.isEmpty()){
            car.setAvailable(available);
            car.setAvailble_city(availableCity);
            car.setBrand(brand);
            car.setMaintenance_certificate(expired);
            car.setManufactured_year(manufacturedYear);
            car.setMax_seats(maxiSeats);
            car.setMin_seats(miniSeats);
            car.setModel_num(modelNum);
            car.setSerial_num(serialNo);
            JOptionPane.showMessageDialog(null, "Updated Car successfully!");
        }
        else {
            String errorLog="";
            for(String message: messageLog)
            errorLog+=message+"\n";
            JOptionPane.showMessageDialog(null,errorLog);
        }
        //JOptionPane.showMessageDialog(null, "Registered Car successfully!");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtManufacturedYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturedYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturedYearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox checkExpired;
    private javax.swing.JCheckBox checkYes;
    private javax.swing.JLabel labelAvailable;
    private javax.swing.JLabel labelAvailableCity;
    private javax.swing.JLabel labelBrand;
    private javax.swing.JLabel labelMaintCertStatus;
    private javax.swing.JLabel labelManufacturedYear;
    private javax.swing.JLabel labelMaxSeats;
    private javax.swing.JLabel labelMinSeats;
    private javax.swing.JLabel labelModelNo;
    private javax.swing.JLabel labelRegister;
    private javax.swing.JLabel labelSerialNo;
    private javax.swing.JTextField txtAvailableCity;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtManufacturedYear;
    private javax.swing.JTextField txtMaxSeats;
    private javax.swing.JTextField txtMinSeats;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtSerialNo;
    // End of variables declaration//GEN-END:variables
}
