/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import BusinessModel.Car;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author pavanrao
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    
    private Car car;
    private boolean isImageUploaded = false;
    private BufferedImage carImage;
    public CreatePanel(Car car) {
        initComponents();
        this.car = car;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageTextField = new javax.swing.JTextField();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        engineDisplacementTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        engineCompressionRatioTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        companyLabel = new javax.swing.JLabel();
        companyTextField = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        startingPriceLabel = new javax.swing.JLabel();
        engineLitresLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        engineHorsePowerLabel = new javax.swing.JLabel();
        engineTorqueLabel = new javax.swing.JLabel();
        transmissionTypeLabel = new javax.swing.JLabel();
        topSpeedLabel = new javax.swing.JLabel();
        fuelTankCapacityLabel = new javax.swing.JLabel();
        tireTypeLabel = new javax.swing.JLabel();
        wheelDimensionLabel = new javax.swing.JLabel();
        tireDimensionLabel = new javax.swing.JLabel();
        lwhLabel = new javax.swing.JLabel();
        curbWeightlabel = new javax.swing.JLabel();
        createCar = new javax.swing.JButton();
        curbWeightTextField = new javax.swing.JTextField();
        lwhTextField = new javax.swing.JTextField();
        tireDimensionTextField = new javax.swing.JTextField();
        wheelDimensionTextField = new javax.swing.JTextField();
        tireTypeTextField = new javax.swing.JTextField();
        fuelTankCapacityTextField = new javax.swing.JTextField();
        topSpeedTextField = new javax.swing.JTextField();
        transmissionTypeTextField = new javax.swing.JTextField();
        engineTorqueTextField = new javax.swing.JTextField();
        engineHPTextField = new javax.swing.JTextField();
        engineLtrsTextField = new javax.swing.JTextField();
        startingPriceTextField = new javax.swing.JTextField();
        colorTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        uploadImage = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel9.setText("ENGINE COMPRESSION RATIO (:1)");

        jLabel21.setText("IMAGE");

        setBackground(new java.awt.Color(204, 204, 204));
        setToolTipText("");

        companyLabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        companyLabel.setText("COMPANY");

        companyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyTextFieldActionPerformed(evt);
            }
        });

        modelLabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        modelLabel.setText("MODEL");

        colorLabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        colorLabel.setText("COLOR");

        startingPriceLabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        startingPriceLabel.setText("STARTING PRICE");

        engineLitresLabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        engineLitresLabel.setText("ENGINE LITRES");

        jLabel6.setText("ENGINE DISPLACEMENT (cc)");

        engineHorsePowerLabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        engineHorsePowerLabel.setText("ENGINE HORSEPOWER (bhp)");

        engineTorqueLabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        engineTorqueLabel.setText("ENGINE TORQUE (lb-ft @ rpm)");

        transmissionTypeLabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        transmissionTypeLabel.setText("TRANSMISSION TYPE");

        topSpeedLabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        topSpeedLabel.setText("TOP SPEED (mph)");

        fuelTankCapacityLabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        fuelTankCapacityLabel.setText("FUEL TANK CAPACITY (gallons)");

        tireTypeLabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        tireTypeLabel.setText("TIRE TYPE");

        wheelDimensionLabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        wheelDimensionLabel.setText("WHEEL DIMENSION (in)");

        tireDimensionLabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        tireDimensionLabel.setText("TIRE DIMENSION (mm)");

        lwhLabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        lwhLabel.setText("EXTERIOR LENGTH, WIDTH, HEIGHT (in)");

        curbWeightlabel.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        curbWeightlabel.setText("CURB WEIGHT (lbs)");

        createCar.setFont(new java.awt.Font("Chalkboard", 1, 18)); // NOI18N
        createCar.setText("CREATE ");
        createCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCarActionPerformed(evt);
            }
        });

        curbWeightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curbWeightTextFieldActionPerformed(evt);
            }
        });

        transmissionTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transmissionTypeTextFieldActionPerformed(evt);
            }
        });

        engineTorqueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineTorqueTextFieldActionPerformed(evt);
            }
        });

        colorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorTextFieldActionPerformed(evt);
            }
        });

        modelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextFieldActionPerformed(evt);
            }
        });

        uploadImage.setFont(new java.awt.Font("Chalkboard", 1, 18)); // NOI18N
        uploadImage.setText("UPLOAD IMAGE");
        uploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImageActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(204, 204, 255));
        jLabel16.setFont(new java.awt.Font("Chalkboard", 1, 24)); // NOI18N
        jLabel16.setText("CREATE YOUR OWN CAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(334, 334, 334))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(companyLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(modelLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(colorLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(startingPriceLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(engineLitresLabel))
                            .addComponent(engineTorqueLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(engineHorsePowerLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(transmissionTypeLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(engineHPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transmissionTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(companyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(startingPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(engineLtrsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(engineTorqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lwhLabel)
                                        .addGap(7, 7, 7)
                                        .addComponent(lwhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(141, 141, 141)
                                                .addComponent(tireTypeLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(wheelDimensionLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(tireDimensionLabel)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tireDimensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tireTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(wheelDimensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(146, 146, 146)
                                            .addComponent(curbWeightlabel)
                                            .addGap(6, 6, 6)
                                            .addComponent(curbWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(createCar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(91, 91, 91)
                                                        .addComponent(topSpeedLabel))
                                                    .addComponent(fuelTankCapacityLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(topSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fuelTankCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addComponent(uploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))))
            .addGroup(layout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(jLabel6)
                .addContainerGap(503, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(companyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(startingPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(engineLtrsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tireTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(wheelDimensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tireTypeLabel)
                                        .addGap(14, 14, 14)
                                        .addComponent(wheelDimensionLabel)
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tireDimensionLabel)
                                            .addComponent(tireDimensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(lwhLabel))
                                    .addComponent(lwhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(curbWeightlabel))
                                    .addComponent(curbWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(engineTorqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(engineHPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(transmissionTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(topSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(fuelTankCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(topSpeedLabel)
                                        .addGap(14, 14, 14)
                                        .addComponent(fuelTankCapacityLabel)
                                        .addGap(4, 4, 4))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(companyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(modelLabel)
                        .addGap(14, 14, 14)
                        .addComponent(colorLabel)
                        .addGap(13, 13, 13)
                        .addComponent(startingPriceLabel)
                        .addGap(39, 39, 39)
                        .addComponent(engineLitresLabel)
                        .addGap(14, 14, 14)
                        .addComponent(engineTorqueLabel)
                        .addGap(20, 20, 20)
                        .addComponent(engineHorsePowerLabel)
                        .addGap(11, 11, 11)
                        .addComponent(transmissionTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createCar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void companyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyTextFieldActionPerformed

    private void createCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCarActionPerformed
        // TODO add your handling code here:
        car.setColor(colorTextField.getText());
        car.setCompany(companyTextField.getText());
        car.setCurbWeight(curbWeightTextField.getText());
        car.setEngineLitres(engineLtrsTextField.getText());
        car.setExteriorLWH(lwhTextField.getText());
        car.setFuelTankCapacity(fuelTankCapacityTextField.getText());
        car.setModel(modelTextField.getText());
        car.setStartingPrice(startingPriceTextField.getText());
        car.setTireDimension(tireDimensionTextField.getText());
        car.setTireType(tireTypeTextField.getText());
        car.setTopSpeed(topSpeedTextField.getText());
        car.setTorque(engineTorqueTextField.getText());
        car.setTransmissionType(transmissionTypeTextField.getText());
        car.setWheelDimension(wheelDimensionTextField.getText());
        car.setCompany(companyTextField.getText());
        car.setHorsepower(engineHPTextField.getText());
        //Set the image only when it is uploaded
        if(isImageUploaded) {
            car.setImage(carImage);
         }
        else {
            car.setImage(null);
        }            
        JOptionPane.showMessageDialog(null, "Created Car successfully");

    }//GEN-LAST:event_createCarActionPerformed

    private void curbWeightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curbWeightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curbWeightTextFieldActionPerformed

    private void transmissionTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transmissionTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transmissionTypeTextFieldActionPerformed

    private void engineTorqueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineTorqueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engineTorqueTextFieldActionPerformed

    private void colorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorTextFieldActionPerformed

    private void modelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextFieldActionPerformed

    private void uploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImageActionPerformed
        File fileUploaded = null;
        JFileChooser fileChooser = new JFileChooser("/home"); //set the default location to home in the upload dialog
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG, PNG & GIF Images",
                "jpg", "gif", "png"); //restrict the file upload to only image files
        fileChooser.setFileFilter(filter); //apply the image file filter
        int fileChosenOptionStatus = fileChooser.showOpenDialog(null);
        if (fileChosenOptionStatus == JFileChooser.APPROVE_OPTION) { //when yes or ok is chosen in the dialog
            fileUploaded = fileChooser.getSelectedFile();
            if (fileUploaded != null) {
                try {
                    carImage = ImageIO.read(fileUploaded);
                    car.setImage(carImage); //set car object's image with uploaded image
                    isImageUploaded = true;
                } catch (IOException ex) {
                    Logger.getLogger(CreatePanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                    JOptionPane.showMessageDialog(null, "Your image has been uploaded!");                 
            }
        }
    }//GEN-LAST:event_uploadImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JLabel companyLabel;
    private javax.swing.JTextField companyTextField;
    private javax.swing.JButton createCar;
    private javax.swing.JTextField curbWeightTextField;
    private javax.swing.JLabel curbWeightlabel;
    private javax.swing.JTextField engineCompressionRatioTextField;
    private javax.swing.JTextField engineDisplacementTextField;
    private javax.swing.JTextField engineHPTextField;
    private javax.swing.JLabel engineHorsePowerLabel;
    private javax.swing.JLabel engineLitresLabel;
    private javax.swing.JTextField engineLtrsTextField;
    private javax.swing.JLabel engineTorqueLabel;
    private javax.swing.JTextField engineTorqueTextField;
    private javax.swing.JLabel fuelTankCapacityLabel;
    private javax.swing.JTextField fuelTankCapacityTextField;
    private javax.swing.JTextField imageTextField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lwhLabel;
    private javax.swing.JTextField lwhTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JLabel startingPriceLabel;
    private javax.swing.JTextField startingPriceTextField;
    private javax.swing.JLabel tireDimensionLabel;
    private javax.swing.JTextField tireDimensionTextField;
    private javax.swing.JLabel tireTypeLabel;
    private javax.swing.JTextField tireTypeTextField;
    private javax.swing.JLabel topSpeedLabel;
    private javax.swing.JTextField topSpeedTextField;
    private javax.swing.JLabel transmissionTypeLabel;
    private javax.swing.JTextField transmissionTypeTextField;
    private javax.swing.JButton uploadImage;
    private javax.swing.JLabel wheelDimensionLabel;
    private javax.swing.JTextField wheelDimensionTextField;
    // End of variables declaration//GEN-END:variables
}
